areas["Toadstool Circle"] = {
	author = [[Drazuk]],
	-- player ranges
	low_soft = 1,
	hi_soft = 50,
	low_hard = 0,
	hi_hard = 65,
	-- end player ranges

	-- vnum ranges
	low_m_vnum = 951,
	hi_m_vnum = 1000,
	low_o_vnum = 951,
	hi_o_vnum = 1000,
	low_r_vnum = 951,
	hi_r_vnum = 1000,
	-- end vnum ranges
	resetmsg = [[You hear the faint sound of giggling in the distance...]],
	reset_frequency = 15,
	flags = [[]],
	-- climate
	temp = 3,
	precip = 2,
	wind = 2,
	-- end climate

	mobiles = {},
		mobiles[951] = { name = [[pixie queen nadine regal]],
			short_description = [[Nadine, Queen of the Pixies]],
			long_description = [[A regal pixie sits amongst the vines and smiles as you approach.
]],
			description = [[Nadine, the pixie queen, smiles at you as you approach the throne.  You are a
little nervous, for you recall stories of the strange magic that pixies can
work on visitors.
]],
			act_flags = [[npc sentinel stayarea noassist]],
			affected_by = [[sanctuary flying true_sight iceshield demonsight]],
			align = -1000,
			complex = 1,
			level = 55,
			mobthac0 = 0,
			ac = -195,
			hitdice = { dice = 5, size = 50, plus = 2150 },
			damdice = { dice = 4, size = 5, plus = 48 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 2,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 15,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 2097152,
			immune = 0,
			susceptible = 0,
			attacks = [[33554441]],
			defenses = [[524294]]
			mudprogs = {},
				mudprogs[1] = { type = [[death_prog]], arglist = [[5]], comlist = [==[emote drops to her knees with a scream, her wings tattered and torn...
say Go then!  Take this pixie magic, thief!
scream
rinvoke artifact
]==] },
		}, -- end mobile 951
		mobiles[952] = { name = [[mouse tiny]],
			short_description = [[a tiny mouse]],
			long_description = [[A tiny mouse sniffs around the toadstools.
]],
			description = [[A tiny mouse sniffs about the toadstools, looking for a treat.  Usually used
by the pixies as mounts, this particular mouse is currently on its own.
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[none]],
			align = 0,
			complex = 1,
			level = 7,
			mobthac0 = 0,
			ac = 45,
			hitdice = { dice = 3, size = 6, plus = 110 },
			damdice = { dice = 2, size = 5, plus = 2 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 77,
			class = 3,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs tail]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[0]]
		}, -- end mobile 952
		mobiles[953] = { name = [[mouse tiny]],
			short_description = [[a tiny mouse]],
			long_description = [[A tiny mouse sniffs around the toadstools.
]],
			description = [[A tiny mouse sniffs about the toadstools, looking for a treat.  Usually used
by the pixies as mounts, this particular mouse is currently on its own.
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[none]],
			align = 0,
			complex = 1,
			level = 7,
			mobthac0 = 0,
			ac = 45,
			hitdice = { dice = 3, size = 6, plus = 110 },
			damdice = { dice = 2, size = 5, plus = 2 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 77,
			class = 3,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs tail]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[0]]
		}, -- end mobile 953
		mobiles[954] = { name = [[mouse tiny]],
			short_description = [[a tiny mouse]],
			long_description = [[A tiny mouse sniffs around the toadstools.
]],
			description = [[A tiny mouse sniffs about the toadstools, looking for a treat.  Usually used
by the pixies as mounts, this particular mouse is currently on its own.
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[none]],
			align = 0,
			complex = 1,
			level = 7,
			mobthac0 = 0,
			ac = 45,
			hitdice = { dice = 3, size = 6, plus = 110 },
			damdice = { dice = 2, size = 5, plus = 2 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 77,
			class = 3,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs tail]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[0]]
		}, -- end mobile 954
		mobiles[955] = { name = [[firefly fly]],
			short_description = [[a glowing firefly]],
			long_description = [[A firefly flits about the toadstools, spreading an eerie green light.
]],
			description = [[A firefly, quite a bit bigger than normal, cruises through the air above you,
casting a spooky green light about the Circle.  Several pixies fly around
harassing it, but it seems to ignore them.
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 15,
			mobthac0 = 0,
			ac = 5,
			hitdice = { dice = 3, size = 6, plus = 250 },
			damdice = { dice = 3, size = 5, plus = 5 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 83,
			class = 3,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head eyestalks wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[0]],
			defenses = [[0]]
		}, -- end mobile 955
		mobiles[956] = { name = [[fae blue Corinna]],
			short_description = [[Corinna the Blue Fae]],
			long_description = [[Corinna sits in her hollow tree, mixing magical liquids together.
]],
			description = [[Corinna looks a bit like a pixie, but is instead a Blue Fae, quite a
distinction as far as the pixies are concerned.  A bit larger than the normal
pixie, Nadine lets her dwell in the Circle, as long as she keeps making
magical potions for her use.
]],
			act_flags = [[npc sentinel stayarea noassist]],
			affected_by = [[sanctuary flying true_sight iceshield demonsight]],
			align = 0,
			complex = 1,
			level = 55,
			mobthac0 = 0,
			ac = -195,
			hitdice = { dice = 5, size = 50, plus = 2150 },
			damdice = { dice = 4, size = 5, plus = 48 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 2,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 0,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[33554441]],
			defenses = [[524294]]
		}, -- end mobile 956
		mobiles[957] = { name = [[firefly fly]],
			short_description = [[a glowing firefly]],
			long_description = [[A firefly flits about the toadstools, spreading an eerie green light.
]],
			description = [[A firefly, quite a bit bigger than normal, cruises through the air above you,
casting a spooky green light about the Circle.  Several pixies fly around
harassing it, but it seems to ignore them.
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 15,
			mobthac0 = 0,
			ac = 5,
			hitdice = { dice = 3, size = 6, plus = 250 },
			damdice = { dice = 3, size = 5, plus = 5 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 83,
			class = 3,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head eyestalks wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[0]],
			defenses = [[0]]
		}, -- end mobile 957
		mobiles[958] = { name = [[pixie guardian]],
			short_description = [[a guardian pixie]],
			long_description = [[A small pixie wearing the badge of the Circle flies about, keeping watch.
]],
			description = [[A young male pixie flies about the Circle, keeping an eye out for any
trouble...well, any trouble that another pixie isn't causing!
]],
			act_flags = [[npc stayarea guardian]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 30,
			mobthac0 = 0,
			ac = -70,
			hitdice = { dice = 4, size = 15, plus = 760 },
			damdice = { dice = 3, size = 5, plus = 20 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 1,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 21,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart brains wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[16777217]],
			defenses = [[0]]
		}, -- end mobile 958
		mobiles[959] = { name = [[pixie guardian]],
			short_description = [[a guardian pixie]],
			long_description = [[A small pixie wearing the badge of the Circle flies about, keeping watch.
]],
			description = [[A young male pixie flies about the Circle, keeping an eye out for any
trouble...well, any trouble that another pixie isn't causing!
]],
			act_flags = [[npc stayarea guardian]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 30,
			mobthac0 = 0,
			ac = -70,
			hitdice = { dice = 4, size = 15, plus = 760 },
			damdice = { dice = 3, size = 5, plus = 20 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 1,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 21,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart brains wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[16777217]],
			defenses = [[0]]
		}, -- end mobile 959
		mobiles[960] = { name = [[pixie guardian]],
			short_description = [[a guardian pixie]],
			long_description = [[A small pixie wearing the badge of the Circle flies about, keeping watch.
]],
			description = [[A young male pixie flies about the Circle, keeping an eye out for any
trouble...well, any trouble that another pixie isn't causing!
]],
			act_flags = [[npc stayarea guardian]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 30,
			mobthac0 = 0,
			ac = -70,
			hitdice = { dice = 4, size = 15, plus = 760 },
			damdice = { dice = 3, size = 5, plus = 20 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 1,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 21,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart brains wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[16777217]],
			defenses = [[0]]
		}, -- end mobile 960
		mobiles[961] = { name = [[boggart Francis pixie twisted]],
			short_description = [[Francis, the dark boggart]],
			long_description = [[A strange, twisted pixie sits atop the huge toadstool.
]],
			description = [[As you gaze upon the strange pixie, you realize that this creature is instead
a boggart, a pixie "gone bad".  While most pixies are all about tricks and
pranks, this one may actually try to cause real harm.
]],
			act_flags = [[npc sentinel stayarea guildmaster scholar noassist]],
			affected_by = [[sanctuary flying true_sight iceshield demonsight]],
			align = -1000,
			complex = 1,
			level = 55,
			mobthac0 = 0,
			ac = -195,
			hitdice = { dice = 5, size = 50, plus = 2150 },
			damdice = { dice = 4, size = 5, plus = 48 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 1,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 0,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[33554441]],
			defenses = [[524294]]
		}, -- end mobile 961
		mobiles[962] = { name = [[pixie]],
			short_description = [[a pixie]],
			long_description = [[A pixie dances around, singing and laughing to herself.
]],
			description = [[This small pixie is dancing about, singing a bright little tune to herself.
She notices you staring and gives a grin...you hope she hasn't cursed you
along with it!
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 20,
			mobthac0 = 0,
			ac = -20,
			hitdice = { dice = 4, size = 8, plus = 380 },
			damdice = { dice = 3, size = 5, plus = 10 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 2,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 18,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[2]]
		}, -- end mobile 962
		mobiles[963] = { name = [[pixie]],
			short_description = [[a pixie]],
			long_description = [[A pixie dances around, singing and laughing to herself.
]],
			description = [[This small pixie is dancing about, singing a bright little tune to herself.
She notices you staring and gives a grin...you hope she hasn't cursed you
along with it!
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 20,
			mobthac0 = 0,
			ac = -20,
			hitdice = { dice = 4, size = 8, plus = 380 },
			damdice = { dice = 3, size = 5, plus = 10 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 2,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 18,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[2]]
		}, -- end mobile 963
		mobiles[964] = { name = [[pixie]],
			short_description = [[a pixie]],
			long_description = [[A pixie dances around, singing and laughing to herself.
]],
			description = [[This small pixie is dancing about, singing a bright little tune to herself.
She notices you staring and gives a grin...you hope she hasn't cursed you
along with it!
]],
			act_flags = [[npc stayarea noassist]],
			affected_by = [[flying]],
			align = 0,
			complex = 1,
			level = 20,
			mobthac0 = 0,
			ac = -20,
			hitdice = { dice = 4, size = 8, plus = 380 },
			damdice = { dice = 3, size = 5, plus = 10 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 2,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 18,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[rodent]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[head arms legs heart wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[1]],
			defenses = [[2]]
		}, -- end mobile 964
		mobiles[965] = { name = [[thief pixie Caliesten humming sound]],
			short_description = [[the pixie thief, Caliesten]],
			long_description = [[You thought you might of heard a slight humming sound pass your ear...
]],
			description = [[For a split second, you spy in the air, a tiny man.  Dressed in a black
outfit, he flashes you a quick grin, then disappears!  A second later, you
feel a tug on your ear, and a voice whispers, "Thanks for the gift!"
]],
			act_flags = [[npc guildmaster scholar noassist]],
			affected_by = [[sanctuary sneak hide camo pass_door floating true_sight fireshield aqua_breath corrupt demonsight]],
			align = -1000,
			complex = 1,
			level = 65,
			mobthac0 = 0,
			ac = 0,
			hitdice = { dice = 8, size = 1, plus = 0 },
			damdice = { dice = 0, size = 0, plus = 0 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 1,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 4,
			class = 14,
			height = 0,
			weight = 0,
			speaks = 2097151,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[heart wings]],
			resistant = 2105344,
			immune = 0,
			susceptible = 0,
			attacks = [[16909857]],
			defenses = [[524291]]
			mudprogs = {},
				mudprogs[1] = { type = [[rand_prog]], arglist = [[5]], comlist = [==[ponder
say You know, I can "TEACH BLADESONG" if you are advanced enough!
]==] },
				mudprogs[2] = { type = [[speech_prog]], arglist = [['teach bladesong']], comlist = [==[if isnohero($n)
    say Sorry $n, you need to be a hero before you can learn my skill
    smile $n
    break
else
   if questpoints($n) < 15000
       say Sorry $n, you need more quest points to learn my skill
        smile $n
        break
   else
       nod $n
       mppractice $n bladesong 100
       mpmset $n questpoints 15000
       say Use your new skill wisely!
       salute $n
    endif
endif
]==] },
				mudprogs[3] = { type = [[death_prog]], arglist = [[5]], comlist = [==[say Gods!  Its back to the Shadow for me!
groan
rinvoke artifact
]==] },
				mudprogs[4] = { type = [[hitprcnt_prog]], arglist = [[5]], comlist = [==[snarl
if rand(7)
  say No, I refuse to fall!
  else
  if rand(13)
     say I shall not let you slay me!
     else
     if rand(14)
        say You think you are mighty?
        else
        if rand(17)
           say I shall overcome my wounds!
           else
           if rand(20)
              say You cannot defeat me!
              else
              if rand(25)
                 say Death is not an option!
                 else
                 if rand(33)
                    say Must...ignore...the...blood!
                    else
                    if rand(50)
                       say Gods, I am wounded!
                    endif
                 endif
              endif
           endif
        endif
     endif
   endif
endif]==] },
		}, -- end mobile 965
		mobiles[966] = { name = [[firefly flirefy]],
			short_description = [[Flirefy]],
			long_description = [[A small firefly keeps the area well lit.
]],
			description = [[This small firefly belongs to Flutterby. It floats around the toadstool
providing light for the room, which isn't a difficult task since the toadstool
is quite small.
]],
			act_flags = [[npc sentinel]],
			affected_by = [[floating]],
			align = 0,
			complex = 1,
			level = 1,
			mobthac0 = 0,
			ac = 0,
			hitdice = { dice = 8, size = 1, plus = 0 },
			damdice = { dice = 0, size = 0, plus = 0 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 83,
			class = 17,
			height = 0,
			weight = 0,
			speaks = 8,
			speaking = [[insectoid]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[wings]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[0]],
			defenses = [[0]]
		}, -- end mobile 966
		mobiles[1000] = { name = [[Placeholder]],
			short_description = [[Placeholder]],
			long_description = [[Placeholder
]],
			description = [[Someone has abandoned a new mob here
]],
			act_flags = [[npc]],
			affected_by = [[none]],
			align = 0,
			complex = 1,
			level = 1,
			mobthac0 = 0,
			ac = 0,
			hitdice = { dice = 8, size = 1, plus = 0 },
			damdice = { dice = 0, size = 0, plus = 0 },
			gold = 0,
			exp = 0,
			position = 112,
			defposition = 112,
			sex = 0,
			perm_str = 13,
			perm_int = 13,
			perm_wis = 13,
			perm_dex = 13,
			perm_con = 13,
			perm_cha = 13,
			perm_lck = 13,
			saving_damage = 0,
			saving_wand = 0,
			saving_para_petri = 0,
			saving_breath = 0,
			saving_spell_staff = 0,
			race = 0,
			class = 0,
			height = 0,
			weight = 0,
			speaks = 1,
			speaking = [[common]],
			numattacks = 0,
			hitroll = 0,
			damroll = 0,
			xflags = [[]],
			resistant = 0,
			immune = 0,
			susceptible = 0,
			attacks = [[0]],
			defenses = [[0]]
		}, -- end mobile 1000
	objects = {},
		objects[951] = { name = [[wand crooked]],
		short_description = [[a crooked wand]],
		long_description = [[A strange, crooked wand sits here.]],
		action_description = [==[]==],
		type = [[wand]],
		extra_flags = [[hum magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = 5,
		val2 = 5,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 8500,
		staff_wand_spell = [[curse]],
	}, -- end object 951
		objects[952] = { name = [[wand light wood]],
		short_description = [[a light wood wand]],
		long_description = [[A wand crafted from light wood sits here.]],
		action_description = [==[]==],
		type = [[wand]],
		extra_flags = [[glow magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = 5,
		val2 = 5,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 7000,
		staff_wand_spell = [[cure serious]],
	}, -- end object 952
		objects[953] = { name = [[wand stout]],
		short_description = [[a stout wand]],
		long_description = [[A stout wand sits here.]],
		action_description = [==[]==],
		type = [[wand]],
		extra_flags = [[hum magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = 5,
		val2 = 5,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 15000,
		staff_wand_spell = [[magnetic thrust]],
	}, -- end object 953
		objects[954] = { name = [[wand silvery gleaming]],
		short_description = [[a silvery wand]],
		long_description = [[A silvery, gleaming wand sits here.]],
		action_description = [==[]==],
		type = [[wand]],
		extra_flags = [[magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = 5,
		val2 = 5,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 9000,
		staff_wand_spell = [[shocking grasp]],
	}, -- end object 954
		objects[955] = { name = [[potion glistening]],
		short_description = [[a glistening potion]],
		long_description = [[A potion glistening with light sits here.]],
		action_description = [==[]==],
		type = [[potion]],
		extra_flags = [[glow magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = -1,
		val2 = -1,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 15000,
		pill_potion_scroll_spells = {[[bless]], [[heal]], [[NONE]]},
	}, -- end object 955
		objects[956] = { name = [[potion minty mint]],
		short_description = [[a minty potion]],
		long_description = [[A potion smelling of mint sits here.]],
		action_description = [==[]==],
		type = [[potion]],
		extra_flags = [[magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = -1,
		val2 = -1,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 150,
		pill_potion_scroll_spells = {[[word of recall]], [[NONE]], [[NONE]]},
	}, -- end object 956
		objects[957] = { name = [[potion bubbling]],
		short_description = [[a bubbling potion]],
		long_description = [[A bubbling potion sits here.]],
		action_description = [==[]==],
		type = [[potion]],
		extra_flags = [[hum magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = -1,
		val2 = -1,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 2500,
		pill_potion_scroll_spells = {[[kindred strength]], [[NONE]], [[NONE]]},
	}, -- end object 957
		objects[958] = { name = [[potion sour]],
		short_description = [[a sour potion]],
		long_description = [[A sour smelling potion sits here.]],
		action_description = [==[]==],
		type = [[potion]],
		extra_flags = [[magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = -1,
		val2 = -1,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 5000,
		pill_potion_scroll_spells = {[[remove curse]], [[NONE]], [[NONE]]},
	}, -- end object 958
		objects[959] = { name = [[potion bright]],
		short_description = [[a bright potion]],
		long_description = [[A potion, glowing brightly, sits here.]],
		action_description = [==[]==],
		type = [[potion]],
		extra_flags = [[glow magic]],
		wear_flags = [[take hold]],
		val0 = 35,
		val1 = -1,
		val2 = -1,
		val3 = -1,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 30000,
		pill_potion_scroll_spells = {[[restore mana]], [[restore mana]], [[restore mana]]},
	}, -- end object 959
		objects[960] = { name = [[dagger silver]],
		short_description = [[a silver dagger]],
		long_description = [[A small dagger, crafted of fine silver.]],
		action_description = [==[]==],
		type = [[weapon]],
		extra_flags = [[glow]],
		wear_flags = [[take wield]],
		val0 = 12,
		val1 = 2,
		val2 = 4,
		val3 = 11,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 500,
	}, -- end object 960
		objects[961] = { name = [[crown silver]],
		short_description = [[a silver crown]],
		long_description = [[A small crown, crafted from fine silver.]],
		action_description = [==[]==],
		type = [[armor]],
		extra_flags = [[glow magic]],
		wear_flags = [[take head]],
		val0 = 8,
		val1 = 8,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 2,
		cost = 500,
	affects = {},
		affects[1] = { location = [[wisdom]], modifier = 2 },
		affects[2] = { location = [[intelligence]], modifier = 2 },
	}, -- end object 961
		objects[962] = { name = [[gown gossamer]],
		short_description = [[a gossamer gown]],
		long_description = [[A long gown, weaved from a light, airy fabric.]],
		action_description = [==[]==],
		type = [[armor]],
		extra_flags = [[glow magic]],
		wear_flags = [[take body]],
		val0 = 5,
		val1 = 5,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 750,
	affects = {},
		affects[1] = { location = [[spell damage]], modifier = 3 },
		affects[2] = { location = [[save vs spell]], modifier = -4 },
		affects[3] = { location = [[mana]], modifier = 50 },
	}, -- end object 962
		objects[963] = { name = [[spring gurgling]],
		short_description = [[a gurgling spring]],
		long_description = [[A small spring gurgles pleasantly out of the forest floor.]],
		action_description = [==[]==],
		type = [[fountain]],
		extra_flags = [[]],
		wear_flags = [[]],
		val0 = 0,
		val1 = 1,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 0,
	}, -- end object 963
		objects[964] = { name = [[badge circle toadstool]],
		short_description = [[the Badge of the Circle]],
		long_description = [[A small badge, in the shape of a toadstool, lies here.]],
		action_description = [==[]==],
		type = [[armor]],
		extra_flags = [[magic]],
		wear_flags = [[take pride]],
		val0 = 3,
		val1 = 3,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 350,
	affects = {},
		affects[1] = { location = [[save vs spell]], modifier = -2 },
	}, -- end object 964
		objects[965] = { name = [[mushroom toadstool key flutterbykey]],
		short_description = [[a tiny toadstool]],
		long_description = [[An odd mushroom is growing here.]],
		action_description = [==[]==],
		type = [[trash]],
		extra_flags = [[nolocate quest]],
		wear_flags = [[take hold]],
		val0 = 0,
		val1 = 0,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 0,
	}, -- end object 965
		objects[966] = { name = [[loveseat]],
		short_description = [[a small love seat]],
		long_description = [[A small, yet comfortable, love seat invites you to sit down.]],
		action_description = [==[]==],
		type = [[furniture]],
		extra_flags = [[nolocate]],
		wear_flags = [[]],
		val0 = 0,
		val1 = 0,
		val2 = 1161,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 0,
	}, -- end object 966
		objects[1000] = { name = [[Placeholder]],
		short_description = [[Placeholder]],
		long_description = [[Placeholder]],
		action_description = [==[]==],
		type = [[trash]],
		extra_flags = [[]],
		wear_flags = [[]],
		val0 = 0,
		val1 = 0,
		val2 = 0,
		val3 = 0,
		val4 = 0,
		val5 = 0,
		weight = 1,
		cost = 0,
	}, -- end object 1000
	rooms = {},
		rooms[951] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.  South of here lies the Greenpath.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 952},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 339},
	}, -- end room 951
		rooms[952] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 953},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 951},
	}, -- end room 952
		rooms[953] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 954},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 952},
	}, -- end room 953
		rooms[954] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 955},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 953},
	}, -- end room 954
		rooms[955] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 954},
			exits[2] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 956},
	}, -- end room 955
		rooms[956] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 955},
			exits[2] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 957},
	}, -- end room 956
		rooms[957] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 958},
			exits[2] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 956},
			exits[3] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 2401},
	}, -- end room 957
		rooms[958] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 959},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 957},
	}, -- end room 958
		rooms[959] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 960},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 958},
	}, -- end room 959
		rooms[960] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 961},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 959},
	}, -- end room 960
		rooms[961] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads through a lightly forested area.  From what you can tell,
this must be some sort of game path, as it doesn't look liked many humanoids
have traveled along it.  The wind is warm, and an almost "happy" feeling is in
the air.  To the east, the woods thicken up a bit, obscuring your view.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 962},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 960},
	}, -- end room 961
		rooms[962] = { name = [[Through A Light Forest]],
		description = [==[A tiny path leads into a forested area..  From what you can tell, this must be
some sort of game path, as it doesn't look liked many humanoids have traveled
along it.  The wind is warm, and an almost "happy" feeling is in the air.  To
the north lies a small clearing in the trees.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 963},
			exits[2] = { dir = [[w]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 961},
	}, -- end room 962
		rooms[963] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 976},
			exits[2] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 964},
			exits[3] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 962},
			exits[4] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 970},
	}, -- end room 963
		rooms[964] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 965},
			exits[2] = { dir = [[w]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 963},
	}, -- end room 964
		rooms[965] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 966},
			exits[2] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 964},
			exits[3] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 976},
	}, -- end room 965
		rooms[966] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 965},
			exits[2] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 967},
	}, -- end room 966
		rooms[967] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 973},
			exits[2] = { dir = [[e]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 966},
			exits[3] = { dir = [[s]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 976},
			exits[4] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 968},
	}, -- end room 967
		rooms[968] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 967},
			exits[2] = { dir = [[s]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 969},
	}, -- end room 968
		rooms[969] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 968},
			exits[2] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 976},
			exits[3] = { dir = [[s]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 970},
			exits[4] = { dir = [[w]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 971},
	}, -- end room 969
		rooms[970] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  The major landmark here is a
large circle of toadstools.  All about you see sense movement, and
occasionally hear bits of song and laughter.  Each time you turn to look,
nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 969},
			exits[2] = { dir = [[e]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 963},
	}, -- end room 970
		rooms[971] = { name = [[The Hollow Tree]],
		description = [==[A large, hollowed out tree stands here.  Within is what appears to be a small
shop, as little bottles and other magical items sit about on display.  A large
log is placed as a counter in front of the tree.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 969},
	}, -- end room 971
		rooms[972] = { name = [[A Large Toadstool]],
		description = [==[An extra large toadstool stands here.  The area around the toadstool is
carpeted with a bright green grass, which feels like the softest carpet under
your feet.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 973},
	}, -- end room 972
		rooms[973] = { name = [[A Lighted Path]],
		description = [==[A small path leads away from the toadstool circle, and into a smaller clearing
north of you.  While you can't see any apparent lights, this area seems
brighter than the surrounding forest.  You hear the sound of music and singing
north of here.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 975},
			exits[2] = { dir = [[e]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 974},
			exits[3] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 967},
			exits[4] = { dir = [[w]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 972},
	}, -- end room 973
		rooms[974] = { name = [[The Mystic Spring]],
		description = [==[A sparkling spring of water sits in a circle of trees here.  The sound of the
gurgling spring is calming and makes you feel better just standing here.  A
feeling of safety emanates from the clearing.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[e]], description = [[]], keyword = [[]],
						info = 41944103, key = 965, vnum = 977},
			exits[2] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 973},
	}, -- end room 974
		rooms[975] = { name = [[Circle Of The Court]],
		description = [==[You enter a brightly lit clearing in the forest.  On the north end of the
clearing lies a tree, whose roots seem to form what looks like a chair, or
perhaps a throne.  Bright green vines intertwine with the roots, and the smell
of mint fills the air.
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[s]], description = [[]], keyword = [[]],
						info = 0, key = 0, vnum = 973},
	}, -- end room 975
		rooms[976] = { name = [[The Toadstool Circle]],
		description = [==[You stand in a small clearing in the forest.  As you look about, you realize
you stand in the exact center of the ring of toadstools.  All about you see
sense movement, and occasionally here bits of song and laughter.  Each time
you turn to look, nothing is there!
]==],
		flags = 0,
		sector = 3,
		exits = {},
			exits[1] = { dir = [[n]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 967},
			exits[2] = { dir = [[e]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 965},
			exits[3] = { dir = [[s]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 963},
			exits[4] = { dir = [[w]], description = [[Exit description]], keyword = [[Exit description]],
						info = 0, key = 0, vnum = 969},
	}, -- end room 976
		rooms[977] = { name = [[Inside Flutterby's Toadstool]],
		description = [==[The inside is small for human standards, but for a pixie it's nice and roomy.
The room is rounded and the walls are lined with shelves filled with various
types of jars and other containers. The floor is covered with a woven grass
rug. A small firefly floats around the ceiling, providing much needed light
inside the otherwise dark room.
]==],
		flags = 268436492,
		sector = 0,
		exits = {},
			exits[1] = { dir = [[w]], description = [[]], keyword = [[]],
						info = 41944103, key = 965, vnum = 974},
	}, -- end room 977
		rooms[1000] = { name = [[Pains]],
		description = [==[Placeholder
test
]==],
		flags = 1073741828,
		sector = 3,
	}, -- end room 1000
	resets = {},
		resets[1] = {command = "O", extra = 0, arg1 = 966, arg2 = 1, arg3 = 977},
		resets[2] = {command = "D", extra = 0, arg1 = 977, arg2 = 3, arg3 = 2},
		resets[3] = {command = "M", extra = 0, arg1 = 966, arg2 = 1, arg3 = 977},
		resets[4] = {command = "M", extra = 0, arg1 = 965, arg2 = 1, arg3 = 967},
		resets[5] = {command = "O", extra = 0, arg1 = 963, arg2 = 1, arg3 = 974},
		resets[6] = {command = "M", extra = 0, arg1 = 964, arg2 = 2, arg3 = 967},
		resets[7] = {command = "M", extra = 0, arg1 = 964, arg2 = 2, arg3 = 967},
		resets[8] = {command = "M", extra = 0, arg1 = 963, arg2 = 2, arg3 = 961},
		resets[9] = {command = "M", extra = 0, arg1 = 963, arg2 = 2, arg3 = 961},
		resets[10] = {command = "M", extra = 0, arg1 = 962, arg2 = 2, arg3 = 974},
		resets[11] = {command = "M", extra = 0, arg1 = 962, arg2 = 2, arg3 = 974},
		resets[12] = {command = "M", extra = 0, arg1 = 960, arg2 = 2, arg3 = 963},
		resets[13] = {command = "E", extra = 0, arg1 = 964, arg2 = 1, arg3 = 25},
		resets[14] = {command = "M", extra = 0, arg1 = 960, arg2 = 2, arg3 = 963},
		resets[15] = {command = "M", extra = 0, arg1 = 959, arg2 = 2, arg3 = 976},
		resets[16] = {command = "E", extra = 0, arg1 = 964, arg2 = 1, arg3 = 25},
		resets[17] = {command = "M", extra = 0, arg1 = 959, arg2 = 2, arg3 = 976},
		resets[18] = {command = "M", extra = 0, arg1 = 958, arg2 = 2, arg3 = 975},
		resets[19] = {command = "E", extra = 0, arg1 = 964, arg2 = 1, arg3 = 25},
		resets[20] = {command = "M", extra = 0, arg1 = 958, arg2 = 2, arg3 = 975},
		resets[21] = {command = "M", extra = 0, arg1 = 957, arg2 = 2, arg3 = 964},
		resets[22] = {command = "M", extra = 0, arg1 = 957, arg2 = 2, arg3 = 964},
		resets[23] = {command = "M", extra = 0, arg1 = 955, arg2 = 2, arg3 = 970},
		resets[24] = {command = "M", extra = 0, arg1 = 955, arg2 = 2, arg3 = 970},
		resets[25] = {command = "M", extra = 0, arg1 = 954, arg2 = 2, arg3 = 973},
		resets[26] = {command = "M", extra = 0, arg1 = 954, arg2 = 2, arg3 = 973},
		resets[27] = {command = "M", extra = 0, arg1 = 953, arg2 = 2, arg3 = 963},
		resets[28] = {command = "M", extra = 0, arg1 = 953, arg2 = 2, arg3 = 963},
		resets[29] = {command = "M", extra = 0, arg1 = 952, arg2 = 2, arg3 = 952},
		resets[30] = {command = "M", extra = 0, arg1 = 952, arg2 = 2, arg3 = 952},
		resets[31] = {command = "M", extra = 0, arg1 = 961, arg2 = 1, arg3 = 972},
		resets[32] = {command = "G", extra = 1, arg1 = 954, arg2 = 1},
		resets[33] = {command = "G", extra = 1, arg1 = 953, arg2 = 1},
		resets[34] = {command = "G", extra = 1, arg1 = 952, arg2 = 1},
		resets[35] = {command = "G", extra = 1, arg1 = 951, arg2 = 1},
		resets[36] = {command = "M", extra = 0, arg1 = 956, arg2 = 1, arg3 = 971},
		resets[37] = {command = "G", extra = 1, arg1 = 959, arg2 = 1},
		resets[38] = {command = "G", extra = 1, arg1 = 958, arg2 = 1},
		resets[39] = {command = "G", extra = 1, arg1 = 957, arg2 = 1},
		resets[40] = {command = "G", extra = 1, arg1 = 956, arg2 = 1},
		resets[41] = {command = "G", extra = 1, arg1 = 955, arg2 = 1},
		resets[42] = {command = "M", extra = 0, arg1 = 951, arg2 = 1, arg3 = 975},
		resets[43] = {command = "E", extra = 0, arg1 = 962, arg2 = 1, arg3 = 7},
		resets[44] = {command = "E", extra = 0, arg1 = 961, arg2 = 1, arg3 = 1},
	shops = {},
		shops[1] = {keeper = 956, type1 = 2, type2 = 10, type3 = 8, type4 = 0, type5 = 0, profit_buy = 120, profit_sell = 90, }, -- Corinna the Blue Fae
		shops[2] = {keeper = 961, type1 = 3, type2 = 4, type3 = 8, type4 = 0, type5 = 0, profit_buy = 120, profit_sell = 90, }, -- Francis, the dark boggart
	repairs = {},
	specials = {},
		specials[1] = {vnum = 951, spec = [[spec_cast_archmagi]]},
		specials[2] = {vnum = 956, spec = [[spec_cast_druid]]},
		specials[3] = {vnum = 958, spec = [[spec_guard]]},
		specials[4] = {vnum = 959, spec = [[spec_guard]]},
		specials[5] = {vnum = 960, spec = [[spec_guard]]},
		specials[6] = {vnum = 961, spec = [[spec_cast_diabolist]]},
		specials[7] = {vnum = 965, spec = [[spec_thief]]},
}
