/**
 * GENERATED by scripts/gen-icons.mjs — do not edit by hand.
 * Attribution for the game-icons.net icons the client bundles. game-icons.net art is licensed
 * CC BY 3.0, which REQUIRES crediting the original artist — this list is rendered verbatim in
 * the in-app Credits screen. Each author was verified against the icon's canonical game-icons.net
 * page. Regenerate with: node scripts/gen-icons.mjs
 */
export interface IconCredit { slug: string; title: string; author: string; role: string; url: string; }

export const ICON_LICENSE = { name: "CC BY 3.0", url: "https://creativecommons.org/licenses/by/3.0/" };
export const ICON_SOURCE = { name: "game-icons.net", url: "https://game-icons.net/" };

/** The distinct artists whose work is bundled (for the Credits summary line). */
export const ICON_ARTISTS: string[] = ["Delapouite","Lorc","Skoll","Zeromancer","sbed"];

/** One row per icon actually used, sorted by artist then title. */
export const ICON_CREDITS: IconCredit[] = [
  { slug: "chest-armor", title: "Chest armor", author: "Delapouite", role: "body equipment slot", url: "https://game-icons.net/1x1/delapouite/chest-armor.html" },
  { slug: "guards", title: "Guards", author: "Delapouite", role: "guard / soldier enemy", url: "https://game-icons.net/1x1/delapouite/guards.html" },
  { slug: "player-base", title: "Player base", author: "Delapouite", role: "your own token", url: "https://game-icons.net/1x1/delapouite/player-base.html" },
  { slug: "position-marker", title: "Position marker", author: "Delapouite", role: "minimap marker", url: "https://game-icons.net/1x1/delapouite/position-marker.html" },
  { slug: "rat", title: "Rat", author: "Delapouite", role: "vermin enemy", url: "https://game-icons.net/1x1/delapouite/rat.html" },
  { slug: "spartan-helmet", title: "Spartan helmet", author: "Delapouite", role: "head equipment slot", url: "https://game-icons.net/1x1/delapouite/spartan-helmet.html" },
  { slug: "sword-brandish", title: "Sword brandish", author: "Delapouite", role: "normal stance", url: "https://game-icons.net/1x1/delapouite/sword-brandish.html" },
  { slug: "two-coins", title: "Two coins", author: "Delapouite", role: "gold", url: "https://game-icons.net/1x1/delapouite/two-coins.html" },
  { slug: "wolverine-claws", title: "Wolverine claws", author: "Delapouite", role: "berserk stance", url: "https://game-icons.net/1x1/delapouite/wolverine-claws.html" },
  { slug: "boots", title: "Boots", author: "Lorc", role: "movement", url: "https://game-icons.net/1x1/lorc/boots.html" },
  { slug: "cowled", title: "Cowled", author: "Lorc", role: "generic humanoid enemy", url: "https://game-icons.net/1x1/lorc/cowled.html" },
  { slug: "crossed-swords", title: "Crossed swords", author: "Lorc", role: "aggressive stance", url: "https://game-icons.net/1x1/lorc/crossed-swords.html" },
  { slug: "dodging", title: "Dodging", author: "Lorc", role: "evasive stance", url: "https://game-icons.net/1x1/lorc/dodging.html" },
  { slug: "imp", title: "Imp", author: "Lorc", role: "demon enemy", url: "https://game-icons.net/1x1/lorc/imp.html" },
  { slug: "knapsack", title: "Knapsack", author: "Lorc", role: "inventory", url: "https://game-icons.net/1x1/lorc/knapsack.html" },
  { slug: "laurels", title: "Laurels", author: "Lorc", role: "experience / level", url: "https://game-icons.net/1x1/lorc/laurels.html" },
  { slug: "magic-swirl", title: "Magic swirl", author: "Lorc", role: "mana", url: "https://game-icons.net/1x1/lorc/magic-swirl.html" },
  { slug: "run", title: "Run", author: "Lorc", role: "flee action", url: "https://game-icons.net/1x1/lorc/run.html" },
  { slug: "snake", title: "Snake", author: "Lorc", role: "serpent enemy", url: "https://game-icons.net/1x1/lorc/snake.html" },
  { slug: "spectre", title: "Spectre", author: "Lorc", role: "undead / ghost enemy", url: "https://game-icons.net/1x1/lorc/spectre.html" },
  { slug: "wolf-head", title: "Wolf head", author: "Lorc", role: "canine enemy", url: "https://game-icons.net/1x1/lorc/wolf-head.html" },
  { slug: "shield", title: "Shield", author: "sbed", role: "defensive stance", url: "https://game-icons.net/1x1/sbed/shield.html" },
  { slug: "tombstone", title: "Tombstone", author: "sbed", role: "death marker", url: "https://game-icons.net/1x1/sbed/tombstone.html" },
  { slug: "gladius", title: "Gladius", author: "Skoll", role: "engage action + weapon slot", url: "https://game-icons.net/1x1/skoll/gladius.html" },
  { slug: "heart-plus", title: "Heart plus", author: "Zeromancer", role: "health", url: "https://game-icons.net/1x1/zeromancer/heart-plus.html" },
];
