/**
 * GENERATED by scripts/gen-icons.mjs — do not edit by hand.
 * Attribution for the game-icons.net icons the client bundles. game-icons.net art is licensed
 * CC BY 3.0, which REQUIRES crediting the original artist — this list is rendered verbatim in
 * the in-app Credits screen. Each author was verified against the icon's canonical game-icons.net
 * page. Regenerate with: node scripts/gen-icons.mjs
 */
export interface IconCredit { slug: string; title: string; author: string; role: string; url: string; }

export const ICON_LICENSE = { name: "CC BY 3.0", url: "https://creativecommons.org/licenses/by/3.0/" };
export const ICON_SOURCE = { name: "game-icons.net", url: "https://game-icons.net/" };

/** The distinct artists whose work is bundled (for the Credits summary line). */
export const ICON_ARTISTS: string[] = ["Carl Olsen","Caro Asercion","Delapouite","Lorc","Skoll","Zeromancer","sbed"];

/** One row per icon actually used, sorted by artist then title. */
export const ICON_CREDITS: IconCredit[] = [
  { slug: "spider-alt", title: "Spider", author: "Carl Olsen", role: "spider / arachnid enemy", url: "https://game-icons.net/1x1/carl-olsen/spider-alt.html" },
  { slug: "round-potion", title: "Round potion", author: "Caro Asercion", role: "potion / pill / salve item", url: "https://game-icons.net/1x1/caro-asercion/round-potion.html" },
  { slug: "bat", title: "Bat", author: "Delapouite", role: "bat enemy", url: "https://game-icons.net/1x1/delapouite/bat.html" },
  { slug: "chest-armor", title: "Chest armor", author: "Delapouite", role: "body equipment slot", url: "https://game-icons.net/1x1/delapouite/chest-armor.html" },
  { slug: "goblin-head", title: "Goblin head", author: "Delapouite", role: "goblin / kobold enemy", url: "https://game-icons.net/1x1/delapouite/goblin-head.html" },
  { slug: "guards", title: "Guards", author: "Delapouite", role: "guard / soldier enemy", url: "https://game-icons.net/1x1/delapouite/guards.html" },
  { slug: "ogre", title: "Ogre", author: "Delapouite", role: "ogre / giant enemy", url: "https://game-icons.net/1x1/delapouite/ogre.html" },
  { slug: "orc-head", title: "Orc head", author: "Delapouite", role: "orc enemy", url: "https://game-icons.net/1x1/delapouite/orc-head.html" },
  { slug: "player-base", title: "Player base", author: "Delapouite", role: "your own token", url: "https://game-icons.net/1x1/delapouite/player-base.html" },
  { slug: "position-marker", title: "Position marker", author: "Delapouite", role: "minimap marker", url: "https://game-icons.net/1x1/delapouite/position-marker.html" },
  { slug: "rat", title: "Rat", author: "Delapouite", role: "vermin enemy", url: "https://game-icons.net/1x1/delapouite/rat.html" },
  { slug: "ring", title: "Ring", author: "Delapouite", role: "treasure / jewelry item", url: "https://game-icons.net/1x1/delapouite/ring.html" },
  { slug: "spartan-helmet", title: "Spartan helmet", author: "Delapouite", role: "head equipment slot", url: "https://game-icons.net/1x1/delapouite/spartan-helmet.html" },
  { slug: "sword-brandish", title: "Sword brandish", author: "Delapouite", role: "normal stance", url: "https://game-icons.net/1x1/delapouite/sword-brandish.html" },
  { slug: "torch", title: "Torch", author: "Delapouite", role: "light-source item", url: "https://game-icons.net/1x1/delapouite/torch.html" },
  { slug: "two-coins", title: "Two coins", author: "Delapouite", role: "gold", url: "https://game-icons.net/1x1/delapouite/two-coins.html" },
  { slug: "wolverine-claws", title: "Wolverine claws", author: "Delapouite", role: "berserk stance", url: "https://game-icons.net/1x1/delapouite/wolverine-claws.html" },
  { slug: "boots", title: "Boots", author: "Lorc", role: "movement", url: "https://game-icons.net/1x1/lorc/boots.html" },
  { slug: "cat", title: "Cat", author: "Lorc", role: "feline enemy", url: "https://game-icons.net/1x1/lorc/cat.html" },
  { slug: "cowled", title: "Cowled", author: "Lorc", role: "generic humanoid enemy", url: "https://game-icons.net/1x1/lorc/cowled.html" },
  { slug: "crossed-swords", title: "Crossed swords", author: "Lorc", role: "aggressive stance", url: "https://game-icons.net/1x1/lorc/crossed-swords.html" },
  { slug: "crystal-wand", title: "Crystal wand", author: "Lorc", role: "wand item", url: "https://game-icons.net/1x1/lorc/crystal-wand.html" },
  { slug: "dodging", title: "Dodging", author: "Lorc", role: "evasive stance", url: "https://game-icons.net/1x1/lorc/dodging.html" },
  { slug: "dragon-head", title: "Dragon head", author: "Lorc", role: "dragon / reptile enemy", url: "https://game-icons.net/1x1/lorc/dragon-head.html" },
  { slug: "imp", title: "Imp", author: "Lorc", role: "demon enemy", url: "https://game-icons.net/1x1/lorc/imp.html" },
  { slug: "key", title: "Key", author: "Lorc", role: "key item", url: "https://game-icons.net/1x1/lorc/key.html" },
  { slug: "knapsack", title: "Knapsack", author: "Lorc", role: "inventory", url: "https://game-icons.net/1x1/lorc/knapsack.html" },
  { slug: "laurels", title: "Laurels", author: "Lorc", role: "experience / level", url: "https://game-icons.net/1x1/lorc/laurels.html" },
  { slug: "locked-chest", title: "Locked chest", author: "Lorc", role: "container item", url: "https://game-icons.net/1x1/lorc/locked-chest.html" },
  { slug: "magic-swirl", title: "Magic swirl", author: "Lorc", role: "mana", url: "https://game-icons.net/1x1/lorc/magic-swirl.html" },
  { slug: "meat", title: "Meat", author: "Lorc", role: "food item", url: "https://game-icons.net/1x1/lorc/meat.html" },
  { slug: "raven", title: "Raven", author: "Lorc", role: "bird enemy", url: "https://game-icons.net/1x1/lorc/raven.html" },
  { slug: "run", title: "Run", author: "Lorc", role: "flee action", url: "https://game-icons.net/1x1/lorc/run.html" },
  { slug: "scroll-unfurled", title: "Scroll unfurled", author: "Lorc", role: "scroll item", url: "https://game-icons.net/1x1/lorc/scroll-unfurled.html" },
  { slug: "snake", title: "Snake", author: "Lorc", role: "serpent enemy", url: "https://game-icons.net/1x1/lorc/snake.html" },
  { slug: "spectre", title: "Spectre", author: "Lorc", role: "undead / ghost enemy", url: "https://game-icons.net/1x1/lorc/spectre.html" },
  { slug: "wizard-staff", title: "Wizard staff", author: "Lorc", role: "staff item", url: "https://game-icons.net/1x1/lorc/wizard-staff.html" },
  { slug: "wolf-head", title: "Wolf head", author: "Lorc", role: "canine enemy", url: "https://game-icons.net/1x1/lorc/wolf-head.html" },
  { slug: "shield", title: "Shield", author: "sbed", role: "defensive stance", url: "https://game-icons.net/1x1/sbed/shield.html" },
  { slug: "tombstone", title: "Tombstone", author: "sbed", role: "death marker", url: "https://game-icons.net/1x1/sbed/tombstone.html" },
  { slug: "gladius", title: "Gladius", author: "Skoll", role: "engage action + weapon slot", url: "https://game-icons.net/1x1/skoll/gladius.html" },
  { slug: "troll", title: "Troll", author: "Skoll", role: "troll enemy", url: "https://game-icons.net/1x1/skoll/troll.html" },
  { slug: "heart-plus", title: "Heart plus", author: "Zeromancer", role: "health", url: "https://game-icons.net/1x1/zeromancer/heart-plus.html" },
];
